### PR TITLE
Stickepipe integtation 

### PR DESCRIPTION
**Pull request by olyaluts**

### CODE REVIEW

**Comment by Pro100Andrey** [comment]
Добрый день. Мы не можем принять Ваш pull request т.к в семпле предоставлен базовый функционал. Возможно Вы хотели обновить ваш Fork?

**Comment by soulfly** [comment]
Feedback:

1) issue with position of the button when we open a chat screen https://www.evernote.com/l/ANhq_HJLh_ZME6kNUPyOopJEJn3j0U1odvUB/image.png

2) Need to integrate it better with https://github.com/QuickBlox/QMChatViewController-ios and https://github.com/QuickBlox/q-municate-services-ios , built it on top of these components, not just inject to chat sample code. So we expect to receive pull requests to these components as well 

- please create a separate table view cell for stickers and add it to QMChatViewController
- please create a separate model for stickers and add it to q-municate-services-ios

3) There are no localized strings

**Comment by olyaluts** [comment]
@soulfly  We already have sticker model (CoreData and NSObject) in StickerPipe pod. Can we use it, or would you like to implement your own model for sticker?

**Comment by Raikerian** [comment]
Hi @olyaluts 

There is no issue with CoreData model of sticker.
Please take a look closer to our [QMChatViewController](https://github.com/QuickBlox/QMChatViewController-ios) and [QMServices](https://github.com/QuickBlox/q-municate-services-ios) projects. Our samples are not a single project. It is also contains both our projects I've already mentioned.

Sticker cells should be located in QMChatViewController, and subclassing QMChatCell of course.

Sticker message model should be located in QMServices. You can use our notification message as an example (see QBChatMessage+QMCustomParameters class). Our notification message using "Notification message" string in message text, and data in custom data. You should do same for sticker messages. Right now you are sending sticker ID in message text and then hijacking lastMessageText of QBChatDialog to display "Sticker message" string.

Localized strings are missing (see Localizable.strings file).
Also all features need to be also implemented in swift sample chat.

P.S. All pull requests should be addressed to the development branch of every project.

**Comment by olyaluts** [comment]
Ok, got it. So here is what I plan to do:

1. Add a new message type —  `QMMessageTypeSticker` and implement new `isSticker` method checking for this type
2. Add custom field for sticker id in [`QBChatMessage+QMCustomParameters.m`](https://github.com/QuickBlox/q-municate-services-ios/blob/c32eddd73cc3b5cc3481610ff0f04b6fbade97e8/QMChatService/QMChatService/Categories/QBChatMessage%2BQMCustomParameters.m). Or would you like me to add a new category for `QBChatMessage`?
3. Implement new `sendStickerMessage` method in `QMChatService` which will build a message with `QMMessageTypeSticker` type and fill in sticker id field.

**Comment by Raikerian** [comment]
@olyaluts You got it right. You can use development pods for that, it will be helpful (see commented lines for QMCVDevelopment and QMServices development in our podfiles).

**Comment by olyaluts** [comment]
@soulfly @Raikerian just sent pull requests to QMChatViewController and q-municate-services-ios. Will update samples right after PRs are accepted.

**Comment by Raikerian** [comment]
@olyaluts I've seen both of your pull requests. QMServices one need some updates.

Now I see the problem in QMChatViewController one, adding a sticker component to QMChatVC is not a good idea (some users may not need it, and this component is requiring AFNetworking). So I think you need to transfer cells and everything from QMChatViewController component to samples (all subclassing should stay the same, the idea of it is correct right now as it is, you got it right). So, QMChatVC should stay untouched overall, you can easily move all classes to samples.

About QMServices, I need to see a working sample code with stickers to talk about it more. Waiting for it.

**Comment by olyaluts** [comment]
@Raikerian  I've updated both pull requests

**Comment by Raikerian** [comment]
@olyaluts can we get working code for samples also?

**Comment by olyaluts** [comment]
@Raikerian  Ok, how can I make sample before you merge my request? Should I add dependency to my repo?

**Comment by Raikerian** [comment]
You can just push your code in this pull request, or close this and open new one (if required).

**Comment by olyaluts** [comment]
@Raikerian  Ok, I can add sample of QMServices to my repo and you can see it there

**Comment by olyaluts** [comment]
@Raikerian  if you want sample in your repo, I have to install pod QMServices with my changes. How should I do this?

**Comment by Raikerian** [comment]
You have already created pull request for every component. In order for me to test it and update to our samples I need your samples code also. No need to link anything from your side. Current pull request for samples (this one) contains old code.

**Comment by olyaluts** [comment]
@Raikerian I've updated sample with dependencies to 908 pods repos. You may now run and test it. 

After my PRs to https://github.com/QuickBlox/q-municate-services-ios and https://github.com/QuickBlox/QMChatViewController-ios are merged, I will change sample dependencies to your pod repo back.

**Comment by Raikerian** [comment]
We are considering to move changes from those subprojects into samples (dependency of AFNetworking is not good for QMChatViewController). But I need to look closer to the project code in this pull request. Can you give me a link for your forked repo, so I can fetch it/push some changes. Thanks.

**Comment by olyaluts** [comment]
@Raikerian QMCVDevelopment -  https://github.com/908Inc/QMChatViewController-ios, QMServicesDevelopment - https://github.com/908Inc/q-municate-services-ios

**Comment by Raikerian** [comment]
And current one (samples)?

**Comment by olyaluts** [comment]
https://github.com/908Inc/quickblox-ios-sdk sample is in sample-chat project

**Comment by Raikerian** [comment]
Okay thank you, we will have a discussion about this in a near days and I will inform you whether we will post some updates in forks or anything else.

**Comment by olyaluts** [comment]
Ok, thanks :)

**Comment by dehimb** [comment]
Hi @Raikerian
What about integration?

**Comment by Raikerian** [comment]
Hi @dehimb 

We will assign a developer for this approximately next week.

**Comment by Raikerian** [comment]
Outdated.

**Pull request closed without merging**
